# Github workflow to compile latex.
# The latest compiled pdf is available as artifact
# Thomas Kueng (2024) https://github.com/tmkueng

name: writeapaper
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: latex
      FILE: Formelsammlung
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #- name: Install TeXlive
      #  run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      #- name: LaTeX compile
      #  working-directory: ${{ env.DIR }}
      #  #run: latexmk -pdf -bibtex ${{ env.FILE }}
      #  run: pdflatex ${{ env.FILE }}; bibtex ${{ env.FILE }}; pdflatex ${{ env.FILE }}; pdflatex ${{ env.FILE }};
      - name: LaTeX
        uses: xu-cheng/texlive-action@v2
        with:
          run: |
              cd ${{ env.DIR }}
              #pdflatex ${{ env.FILE }}
              #bibtex ${{ env.FILE }}
              #pdflatex ${{ env.FILE }}
              #pdflatex ${{ env.FILE }}
              latex ${{ env.FILE }}.tex
              makeindex ${{ env.FILE }}.idx
              latex ${{ env.FILE }}.tex
              dvipdfm ${{ env.FILE }}.dvi
      - name: move
        run: |
            mkdir -p github_artifacts
            mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
  # deploy:
  #   # Edit here if compiling multiple papers
  #   needs: [paper]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         path: ./github_artifacts
  #     - name: move
  #       run: |
  #           mkdir -p github_deploy
  #           mv ./github_artifacts/*/* ./github_deploy
  #     - name: deploy on orphan branch
  #       uses: peaceiris/actions-gh-pages@v4
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./github_deploy
  #         publish_branch: main
  #         force_orphan: true
  # clean:
  #   needs: [deploy]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: delete
  #       uses: geekyeggo/delete-artifact@v4
  #       with:
  #         name: '*.pdf'
